name: Keep clone up to date
variables:
  REMOTE_ADDR: 'https://github.com/pawelpwc/mytestrepo.git'
stages:
  - stage: running_git_commands
    displayName: running_git_commands
    jobs:
      - job: initiate
        displayName: initiate
        continueOnError: false
        steps:
        - checkout: self
          clean: true
          persistCredentials: true
          displayName: run_commands
        - task: mirror-git-repository-vsts-task@1
          inputs:
            sourceGitRepositoryUri: '$(Build.Repository.Uri)'
            sourceGitRepositoryPersonalAccessToken: ''
            sourceGitRepositoryCloneDirectoryName: 'bb'
            destinationGitRepositoryUri: 'https://github.com/pawelpwc/mytestrepo.git'
            destinationGitRepositoryPersonalAccessToken: ''
        # - bash: | 
        #     git clone --mirror "https://koprowskipawel@dev.azure.com/koprowskipawel/GithHubSyncRepo/_git/GithHubSyncRepo"
            # git remote add --mirror=fetch secondary "https://github.com/pawelpwc/mytestrepo.git"
            # git fetch "https://koprowskipawel@dev.azure.com/koprowskipawel/GithHubSyncRepo/_git/GithHubSyncRepo"
            # git push secondary  --all -f