name: Keep clone up to date
variables:
  REMOTE_ADDR: 'https://github.com/pawelpwc/mytestrepo.git'
stages:
  - stage: running_git_commands
    displayName: running_git_commands
    jobs:
      - job: initiate
        displayName: initiate
        continueOnError: false
        steps:
        - checkout: self
          clean: true
          persistCredentials: true
          displayName: run_commands
        - bash: | 
            git checkout main
            git remote add repoGithub $(REMOTE_ADDR)
            git fetch repoGithub main
            git reset --hard repoGithub/main
            git pull --rebase repoGithub main
            git push --force origin main