name: Keep clone up to date
variables:
  REMOTE_ADDR: 'https://github.com/pawelpwc/mytestrepo.git'
stages:
  - stage: running_git_commands
    displayName: running_git_commands
    jobs:
      - job: initiate
        displayName: initiate
        continueOnError: false
        steps:
        - checkout: self
          clean: true
          persistCredentials: true
          displayName: run_commands
        - task: mirror-git-repository-vsts-task@1
          inputs:
            sourceGitRepositoryUri: 'https://dev.azure.com/koprowskipawel/_git/GithHubSyncRepo'
            sourceGitRepositoryPersonalAccessToken: '5kvrypj73x74qvnqcqigg4mwekfmv4bgh3eikt7vwnxlyyddxnmq'
            # sourceVerifySSLCertificate: false
            destinationGitRepositoryUri: 'https://github.com/pawelpwc/mytestrepo.git'
            destinationGitRepositoryPersonalAccessToken: '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'
    # sourceGitRepositoryUri: 'https://github.com/swellaby/vsts-mirror-git-repository.git'
    # sourceVerifySSLCertificate: false
    # destinationGitRepositoryUri: 'https://dev.azure.com/swellaby/OpenSource/_git/mirror2'
    # destinationGitRepositoryPersonalAccessToken: '$(destVar)'
        # - bash: | 
        #     # git clone --mirror "https://koprowskipawel@dev.azure.com/koprowskipawel/GithHubSyncRepo/_git/GithHubSyncRepo"
        #     git remote add --mirror=fetch secondary "https://github.com/pawelpwc/mytestrepo.git"
        #     # git fetch "https://koprowskipawel@dev.azure.com/koprowskipawel/GithHubSyncRepo/_git/GithHubSyncRepo"
        #     git push secondary  --all -f